# The URL the site will be built for
base_url = "https://www.andrew-thorburn.com"
default_language = "en"
title = "The World Aflame"
description = "The ramblings of one developer (flammable)"
author = "Andrew"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "zola-clean-blog"
generate_feed = true
feed_limit = 20

taxonomies = [
    {name = "categories", rss = true, paginate_by=5},
    {name = "tags", rss = true, paginate_by=5},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
render_emoji = true
smart_punctuation = true

[extra]
author = "Andrew"
clean_blog_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/about", name = "About"},
    {url = "$BASE_URL/contact", name = "Contact"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
]
clean_blog_social = [
    {url = "https://twitter.com/nzipsi", icon="fab fa-twitter"},
    {url = "https://mastodon.social/@ipsi", icon="fab fa-mastodon"},
    {url = "https://github.com/ipsi", icon="fab fa-github"},
    {url = "$BASE_URL/atom.xml", icon="fas fa-rss"}
]